// <auto-generated />
using EvanApi1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvanApi1.Migrations
{
    [DbContext(typeof(CoopContext))]
    [Migration("20210215082126_islatest")]
    partial class islatest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EvanApi.models.Account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("accountid")
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            id = "1",
                            accountid = "1",
                            address = "Khusibu",
                            email = "dangolevan@gmail.com",
                            name = "Evan Dangol",
                            phone = "123456789"
                        },
                        new
                        {
                            id = "2",
                            accountid = "2",
                            address = "Kilagal",
                            email = "bso@gmail.com",
                            name = "Bso Amatya",
                            phone = "234567891"
                        });
                });

            modelBuilder.Entity("EvanApi.models.AccountType", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("accounttype")
                        .HasColumnType("text");

                    b.Property<string>("accounttypeid")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AccountType");

                    b.HasData(
                        new
                        {
                            id = "1",
                            accounttype = "Daily",
                            accounttypeid = "1"
                        },
                        new
                        {
                            id = "2",
                            accounttype = "Month",
                            accounttypeid = "2"
                        });
                });

            modelBuilder.Entity("EvanApi.models.Transaction", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("accountid")
                        .HasColumnType("text");

                    b.Property<string>("accounttypeid")
                        .HasColumnType("text");

                    b.Property<string>("amount")
                        .HasColumnType("text");

                    b.Property<double>("balance")
                        .HasColumnType("double");

                    b.Property<string>("created")
                        .HasColumnType("text");

                    b.Property<string>("entry")
                        .HasColumnType("text");

                    b.Property<double>("interest")
                        .HasColumnType("double");

                    b.Property<bool>("islatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            id = "1",
                            accountid = "1",
                            accounttypeid = "1",
                            amount = "100",
                            balance = 100.0,
                            created = "2021-01-01",
                            entry = "Debit",
                            interest = 0.0,
                            islatest = false
                        },
                        new
                        {
                            id = "2",
                            accountid = "2",
                            accounttypeid = "2",
                            amount = "100",
                            balance = 100.0,
                            created = "2021-01-01",
                            entry = "Debit",
                            interest = 0.0,
                            islatest = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
